FROM tensorflow/tensorflow

WORKDIR /home/project_folder

# copy all files from current directory to the container
COPY . .

# install dependencies
# RUN pip install ultralytics

# RUN pip install poetry
# RUN pip install import os
# RUN pip install import zipfile
# RUN pip install import shutil
# RUN pip install pathlib
# RUN pip install requests